name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - qa
      - uat
      - prod
  pull_request:
    branches:
      - develop
      - qa
      - uat
      - prod

jobs:
  # Type checking and linting
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: ESLint check
        run: npm run lint

  # Build verification
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next/
          retention-days: 7

  # Deploy to appropriate environment
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "url=https://finarif.vercel.app" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "environment=uat" >> $GITHUB_OUTPUT
            echo "url=https://finarif-uat.vercel.app" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "environment=qa" >> $GITHUB_OUTPUT
            echo "url=https://finarif-qa.vercel.app" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "url=https://finarif-dev.vercel.app" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Vercel
        run: |
          echo "Would deploy to ${{ steps.env.outputs.environment }}"
          echo "URL: ${{ steps.env.outputs.url }}"
        # Actual Vercel deployment would go here
        # vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
